import {
  PUBLIC_ANALYTICS_ID,
  PUBLIC_APP_LOGIN_URL,
  PUBLIC_APP_SIGNUP_URL,
  PUBLIC_APP_URL,
  PUBLIC_ENVIRONMENT,
  PUBLIC_SEARCH_CONSOLE_VERIFICATION,
  PUBLIC_SITE_URL,
} from 'astro:env/server';

import { validatePublicEnv } from './env';

export const publicConfig = validatePublicEnv({
  PUBLIC_SITE_URL,
  PUBLIC_APP_URL,
  PUBLIC_APP_SIGNUP_URL,
  PUBLIC_APP_LOGIN_URL,
  PUBLIC_ANALYTICS_ID,
  PUBLIC_SEARCH_CONSOLE_VERIFICATION,
  PUBLIC_ENVIRONMENT,
});
